### ISSUE TITLE
IOError: Could not build the egg. MySQL-python

### ISSUE THREAD

**Issue by satybald** [Polychart/builder#4]
I had the following error during install. It looks like in mysql-python 1.2.4 is a bug with installation(https://github.com/Kegbot/kegbot-server/issues/161). Should it be better to changer version to 1.2.5? I've installed this version without any problem. 

---

raise IOError('Could not build the egg.')

IOError: Could not build the egg.

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/satybald/Documents/SEDevelopment/polychart-onprem/virtualenv/build/MySQL-python

**Comment by loesr** [comment]
1.2.5 worked for me as well.  Do not push Django to 1.6x though.

**Comment by xuexue** [comment]
merged!
